### ISSUE TITLE
Module won't load on Centos kernel 3.10.0-862.3.2.el7.x86_64

### ISSUE THREAD

**Issue by Lare** [groeck/devantech#3]
Hello.

I upgraded today my Centos to a newer kernel. The module compiles fine, but module won't load. Modprobe says "invalid argument". When downgraded to last working kernel 3.10.0-693.17.1.el7.x86_64, everything works fine.

Is there possibly some other driver, or can this be fixed? Or should I try to find a different I2C-USB adapter?

**Comment by groeck** [comment]
Something is wrong with your setup. Most likely you are trying to load the module built for the old  kernel.

**Comment by Lare** [comment]
Here is what I did after new kernel:
In driver's source directory
make clean
make && make install
modprobe i2c-devantech-iss
Until this, this has always worked.

**Comment by Lare** [comment]
Thank for quick answer! I double checked my configuration and I really found a problem there. KERNEL_BUILD was pointing to old kernel.

Sorry about this interrupt.
